# Generated by Django 3.0.4 on 2020-03-22 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200321_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 14, 54, 908679), verbose_name='date published'),
        ),
    ]
