# Generated by Django 3.0.4 on 2020-03-22 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 23, 24, 8, 477649), verbose_name='date published'),
        ),
    ]
